---
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
# this prevents package loading message from appearing in the rendered version of your problem set
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
```

```{r}
# Libraries to use
library(tidyverse)
library(ggplot2)
library(ggthemes)
library(ggimage)
library(ggridges)
library(patchwork)
library(GGally)
library(tibble)
library(dplyr) 
library(viridis)

library(openintro)
library(descriptr)
library(assertable)
library(gapminder)
library(stringr)
library(arrow)
library(forcats)
library(scales)
library(cowplot)
library(rvest)
library(robotstxt)
library(png)

library(redav)
library(mi)
```

```{r}
#EF: Need to change link when new dataset uploaded to git *(RC)****************
df_orig <- read_csv("Data/main/master.csv")
# df_orig <- read_csv("https://raw.githubusercontent.com/ss16318/FantasyPremierLeaguePlayerValue/main/Data/main/master.csv")
```

```{r, fig.align = 'center', fig.width=100%}
#reserved for showing 2019 missing weeks
df_missing_wk3637 = df_orig %>%
  select(Season, Week)

ggplot(df_missing_wk3637, aes(Season, factor(Week))) +
  stat_bin2d(aes(fill = after_stat(count)), binwidth = .999999) + 
  ggtitle("Visualization of Data Available by Season and Week") +
  theme(plot.title = element_text(hjust = 0.5)) + 
  scale_fill_gradient(low = "white", high = "blue", limits=c(0,1000))
```

```{r}
# Missing Value (NA) Analysis
plot_missing2 <- function(x, percent = TRUE) {	
  na_count_all <- data.frame(is.na(x)) %>%	
    dplyr::group_by_all() %>%	
    dplyr::count(name = "count", sort = TRUE) %>%	
    dplyr::ungroup() %>%	
    tibble::rownames_to_column("pattern")	
  
  na_count_all <- na_count_all %>% 
    dplyr::mutate(pattern = factor(.data$pattern, levels = nrow(na_count_all):1))
  
  # count the number of columns with missing values; will be used later to determine if there's a "none missing" pattern	
  na_count_all <- na_count_all %>% 	
    dplyr::rowwise() %>%	
    dplyr::mutate(num_missing_cols = sum(dplyr::c_across(where(is.logical))))	
  
  # data frame for missing patterns bar chart	
  na_count_by_pattern <- na_count_all[,c("pattern", "count", "num_missing_cols")]
  na_count_by_pattern$none_missing <- ifelse(na_count_by_pattern$num_missing_cols == 0, TRUE, FALSE)

  # data frame for missing by column bar chart	
  na_count_by_column <- data.frame(is.na(x)) %>%	
    colSums() %>% 	
    sort(decreasing = TRUE) %>% 	
    tibble::enframe(name = "var", value = "count")	
  
  # tidy and sort na_count_all by column counts
  na_count_all_tidy <- na_count_all %>% 	
    tidyr::pivot_longer(where(is.logical), names_to = "variable") %>%	
    dplyr::mutate(variable = factor(.data$variable, levels = na_count_by_column$var))  %>% 	
    dplyr::mutate(none_missing = ifelse(.data$num_missing_cols == 0, TRUE, FALSE))	
  
  # main plot
  main_plot <- ggplot2::ggplot(na_count_all_tidy, ggplot2::aes(.data$variable, .data$pattern, fill = factor(.data$value), alpha = .data$none_missing)) +	
    ggplot2::geom_tile(color = "white") +	
    ggplot2::scale_fill_manual(values = c("grey70", "mediumpurple")) +	
    ggplot2::scale_alpha_manual(values = c(.7, 1)) +	
    ggplot2::ylab("missing pattern") +	
    ggplot2::guides(fill = "none", alpha = "none") +	
    ggplot2::theme_classic(12) + 
    ggplot2::theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) #MODIFICATION
    #ggplot2::theme(axis.text.y = element_text(angle = 90, vjust = 0.5, hjust=1)) #MODIFICATION
  
  # check for "none missing" pattern
  none_missing_pattern <- na_count_by_pattern %>%
    dplyr::filter(.data$none_missing) %>% dplyr::pull(.data$pattern)
  
  if (length(none_missing_pattern) > 0) {	
    main_plot <- main_plot +	
      ggplot2::annotate("text", x = (ncol(na_count_all)-2)/2,	
               y = nrow(na_count_all) + 1 - as.numeric(as.character(none_missing_pattern)),	
               label = "complete cases")	
  }	
  
  # margin plots
  denom <- ifelse(percent, nrow(x)/100, 1)
  
  missing_by_column_plot <- ggplot2::ggplot(na_count_by_column, ggplot2::aes(forcats::fct_inorder(.data$var), .data$count/denom)) +	
    ggplot2::geom_col(fill = "cornflowerblue", alpha = .7) +
    ggplot2::scale_y_continuous(expand = c(0, 0), n.breaks = 3) +	
    ggplot2::xlab("") +
    ggplot2::ylab(ifelse(percent, "% rows \n missing:", "num rows \n missing:")) +	
    ggplot2::theme_linedraw(12) + #modify	
    ggplot2::theme(panel.grid.major.x = ggplot2::element_blank(),	
          panel.grid.minor.x = ggplot2::element_blank()) +
    ggplot2::theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + #MODIFICATION
    ggplot2::theme(axis.text.y = element_text(size = 8)) #MODIFICATION
  
  missing_by_pattern_plot <- 
    ggplot2::ggplot(na_count_by_pattern, ggplot2::aes(.data$pattern, .data$count/denom, alpha = .data$none_missing)) +
    ggplot2::geom_col(fill = "cornflowerblue") +
    ggplot2::coord_flip() +
    ggplot2::scale_y_continuous(expand = c(0, 0), n.breaks = 3) +
    ggplot2::scale_alpha_manual(values = c(.7, 1)) +
    ggplot2::xlab("") +
    ggplot2::ylab(ifelse(percent, "% rows", "row count")) +
    ggplot2::guides(alpha = "none") +
    ggplot2::theme_linedraw(12) +
    ggplot2::theme(panel.grid.major.y = ggplot2::element_blank(), 
          panel.grid.minor.y = ggplot2::element_blank())
  
  if (percent) {	
    missing_by_column_plot <- missing_by_column_plot +
      ggplot2::scale_y_continuous(expand = c(0, 0), n.breaks = 5,
                         limits = c(0, 100))	
    missing_by_pattern_plot <- missing_by_pattern_plot +
      ggplot2::scale_y_continuous(expand = c(0, 0), n.breaks = 5,
                         limits = c(0, 100))	
  }	
  
  missing_by_column_plot + patchwork::plot_spacer() + 	
    main_plot + missing_by_pattern_plot + 	
    patchwork::plot_layout(widths = c(4, 1), heights = c(1, 1))
}
```

```{r}
#lv <- missing_data.frame(df_orig)
#levels(lv@patterns)
```

```{r, fig.align = 'center', fig.width=100%}
plot_missing2(df_orig, percent = TRUE)
```

```{r, fig.align = 'center', fig.width=100%}
# Plotting Minutes Played
df_orig2 = df_orig
df_orig2$Cost <- as.numeric(df_orig$Cost)
df_orig2$TotalPoints <- as.numeric(df_orig$TotalPoints)
df_orig2$PointsLastRound <- as.numeric(df_orig$PointsLastRound)
df_orig2$MinutesPlayed <- as.numeric(df_orig$MinutesPlayed)

df_orig2$Week <- as.numeric(df_orig$Week)

player_histogram <- df_orig2 %>%
  filter((Week == 37 & Season %in% c(2017, 2018, 2020, 2021)) |
         (Week == 35 & Season == 2019)) %>%
  mutate(avg_min_played = MinutesPlayed/Week) %>%
  select(Surname, avg_min_played)

ggplot(player_histogram, aes(avg_min_played)) +
  geom_histogram(binwidth = 1,
  fill="#0072B2", color="black") + #colorblind friendly
  scale_x_continuous(breaks = seq(0, 100, by=5)) +
  ggtitle("Player Count over Average Minutes Played") +
  theme(plot.title = element_text(hjust = 0.5))
```

```{r, fig.align = 'center', fig.width=100%}
# Preprocess and Filtering
# Filter for end of Season and Players with more than 74 points
PointCost <- df_orig[df_orig$Week == 37,]
d <- filter(PointCost, MinutesPlayed/37 >= 45)

#Creates Points per Cost column and adds levels to positions
d <- d %>% 
   mutate(PointPerCost = TotalPoints / Cost) %>%
   mutate(PositionsList =factor(PositionsList, levels=c("DEF", "MID", "FWD")))

#Find averages for TotalPoints, Cost and PointsPerCost
averagePPC <- mean(d$PointPerCost)
averagePoints <- mean(d$TotalPoints)
averageCost <- mean(d$Cost)

#Rename to Bonus Points
d <- d %>% rename("BonusPoints" = "Bonus")

#Add Points from assists
d <- d %>% 
  mutate(AssistPoints = Assists * 3)

#Add Defenders Points from Goals and Clean Sheets
def <- d %>% 
  filter(PositionsList == "DEF") %>%
  mutate(GoalsScoredPoints = GoalsScored * 6) %>%
  mutate(CleanSheetPoints = CleanSheets * 4)

#Add Midfielder Points from Goals and Clean Sheets
mid <- d %>% 
  filter(PositionsList == "MID") %>%
  mutate(GoalsScoredPoints = GoalsScored * 5) %>%
  mutate(CleanSheetPoints = CleanSheets * 1)

#Add Striker Points from Goals and Clean Sheets
fwd <- d %>% 
  filter(PositionsList == "FWD") %>%
  mutate(GoalsScoredPoints = GoalsScored * 3) %>%
  mutate(CleanSheetPoints = CleanSheets * 0)

#Add 
d <- rbind(def, mid, fwd)
```

```{r}
#EF: this is a dataframe of the team name, team full name, and 
#    end position in 2021-2022 premier league table, and images

Place <- c(5, 14, 13, 9, 18, 3, 12, 16, 17, 8, 2, 1, 6, 11, 20, 15, 4, 19, 7, 10)

Team <- c("ARS", "AVL", "BHA", "BRE", "BUR", "CHE", "CRY", "EVE", "LEE", "LEI", 
          "LIV", "MCI", "MUN", "NEW", "NOR", "SOU", "TOT", "WAT", "WHU", "WOL")

Team_name_full <- c("ARSENAL", "ASTON VILLA", "BRENTFORD", "BRIGHTON & HOVE ALBION", 
                    "BURNLEY", "CHELSEA", "CRYSTAL PALACE", "EVERTON", "LEEDS UNITED", 
                    "LEICESTER CITY", "LIVERPOOL", "MANCHESTER CITY", "MANCHESTER UNITED", 
                    "NEWCASTLE UNITED", "NORWICH CITY", "SOUTHAMPTON", "TOTTENHAM HOTSPUR", 
                    "WATFORD", "WEST HAM UNITED", "WOLVERHAMPTON WANDERERS")

# EF: Do Not USE
# Logo <- list( image_read("Workspace/emf_images/ARS.png"), image_read("Workspace/emf_images/AVL.png"),
#              image_read("Workspace/emf_images/BHA.png"), image_read("Workspace/emf_images/BRE.png"), 
#              image_read("Workspace/emf_images/BUR.png"), image_read("Workspace/emf_images/CHE.png"), 
#              image_read("Workspace/emf_images/CRY.png"), image_read("Workspace/emf_images/EVE.png"), 
#              image_read("Workspace/emf_images/LEE.png"), image_read("Workspace/emf_images/LEI.png"), 
#              image_read("Workspace/emf_images/LIV.png"), image_read("Workspace/emf_images/MCI.png"), 
#              image_read("Workspace/emf_images/MUN.png"), image_read("Workspace/emf_images/NEW.png"), 
#              image_read("Workspace/emf_images/NOR.png"), image_read("Workspace/emf_images/SOU.png"), 
#              image_read("Workspace/emf_images/TOT.png"), image_read("Workspace/emf_images/WAT.png"), 
#              image_read("Workspace/emf_images/WHU.png"), image_read("Workspace/emf_images/WOL.png"))


Logo <- list.files(path="Data/emf_images", pattern="*.png")
image = paste0("Data/emf_images", "/", Logo)
df_2021_team_key <- data.frame(Place, Team_name_full, Team, image)
```

```{r, fig.align = 'center', fig.width=100%}
# Plot Total Points against Cost
ggplot(d, aes(x=Cost, y=TotalPoints)) + 
  geom_point(aes(colour = factor(Season))) +
  geom_smooth(method = "loess", se = FALSE, color = 'darkmagenta') +
  ggtitle("Total Points in a Season against Cost with Best Fit Line") +
  xlab("Cost (in Millions)") + 
  ylab("Total Points") +
  labs(colour = "Season") +
  theme_light() +
  scale_x_continuous(labels = label_number(suffix = "", scale = 1e-6), breaks = seq(0,14000000,1000000)) +
  scale_color_colorblind() +
  theme(plot.title = element_text(hjust = 0.5))
```
```{r, fig.align = 'center', fig.width=100%}
d %>%
  ggplot(aes(SelectedByPercent, PointPerCost)) + 
  geom_point(alpha=0.3) +
  xlab("Selected By Percentage") + 
  ylab("Total Points per Cost") + 
  ggtitle("Total Points Per Cost versus Percentage Selected") + 
  scale_x_continuous(breaks = seq(0, 60, by=10)) +
  theme(plot.title = element_text(hjust = 0.5))
```

```{r, fig.align = 'center', fig.width=100%}
#Selected By % Plot
ggplot(d, aes(x=SelectedByPercent, y= 100*(..count..)/sum(..count..))) + 
  geom_histogram(binwidth=2) +
  facet_grid(cols = vars(PositionsList)) +
  ylab("Relative Frequency %")+
  xlab("Selected By %") +
  theme_light() +
  scale_color_colorblind() +
  ggtitle("Relavtive Frequency over Selected-By Percentage") +
  theme(plot.title = element_text(hjust = 0.5))
```


```{r, fig.align = 'center', fig.width=100%}
#Select Top 50 players in each position and the ways they scored points
pointCategories <- d %>%                                      
  arrange(desc(TotalPoints)) %>% 
  group_by(PositionsList) %>%
  slice(1:50) %>%
  ungroup() %>%
  select(  "GoalsScoredPoints", "AssistPoints",  "CleanSheetPoints", "BonusPoints", "PositionsList")

#Parallel Coordinate Plot
ggparcoord(data = pointCategories, columns = 1:4, groupColumn = 5, scale = "globalminmax" , alphaLines = 0.6 , splineFactor = 4) +
  ggtitle("How The Top 50 Performing Players Score Points") + 
  labs(y = "Global MinMax Feature Value", x = "Point Types") +
  labs(colour = "Position") +
  theme_light() +
  scale_color_colorblind() +
  theme(plot.title = element_text(hjust = 0.5))
```


```{r, fig.align = 'center', fig.width=100%}
# NEEDS TITLE
#Boxplot for Points
p1 <- ggplot(d, aes(x=PositionsList, y=TotalPoints)) + 
  geom_boxplot(outlier.size=0.8) +
  xlab("Position") + 
  ylab("Total Points") +
  geom_hline(aes(yintercept= averagePoints, linetype = "Average Points"), colour= 'blue') +
  scale_linetype_manual(name = "", values = c(2, 2), guide = guide_legend(override.aes = list(color = c("blue")))) +
  theme_light() +
  scale_color_colorblind()

#Boxplot for Cost
p2 <- ggplot(d, aes(x=PositionsList, y=Cost)) + 
  geom_boxplot(outlier.size=0.8) +
  xlab("Position") + 
  ylab("Cost") +
  geom_hline(aes(yintercept= averageCost, linetype = "Average Points"), colour= 'deeppink') +
  scale_linetype_manual(name = "", values = c(2, 2), guide = guide_legend(override.aes = list(color = c("purple")))) +
  theme_light() +
  scale_color_colorblind()

#Boxplot for Points per Cost
p3 <- ggplot(d, aes(x=PositionsList, y=PointPerCost)) + 
  geom_boxplot(outlier.size=0.8) +
  xlab("Position") + 
  ylab("Total Points per Cost") +
  geom_hline(aes(yintercept= averagePPC, linetype = "Average Points per Cost"), colour= 'red') +
  scale_linetype_manual(name = "", values = c(2, 2), guide = guide_legend(override.aes = list(color = c("red")))) +
  theme_light() +
  scale_color_colorblind()

#Adding Plots Together
p1 + p2 + p3 + guide_area() + plot_layout(ncol = 2, guides = "collect")
```

```{r}
# EF: Ridgeplot
ridge_teams <- df_orig %>%
  select(Team, Season) %>%
  distinct() %>%
  group_by(Team) %>%
  summarise(count = n()) %>%
  filter(count == 5) %>%
  select(Team)

ridge_teams <- merge(ridge_teams, df_2021_team_key, by="Team")

ridge_data <- merge(df_orig, ridge_teams, by="Team")
ridge_data$Week <- as.numeric(ridge_data$Week)
  
ridge_data_a <- ridge_data %>%
  filter((Week == 37 & Season %in% c(2017, 2018, 2020, 2021)) | 
         (Week == 35 & Season == 2019)) %>%
  filter(MinutesPlayed > 0) %>%
  mutate(avg_min_played = MinutesPlayed / Week)

ridge_data_b <- ridge_data %>%
  filter((Week == 37 & Season %in% c(2017, 2018, 2020, 2021)) | 
         (Week == 35 & Season == 2019)) %>%
  filter(MinutesPlayed > 0) %>%
  mutate(avg_min_played = MinutesPlayed / Week) %>%
  filter(avg_min_played >= 45)
  
```

```{r, fig.align = 'center', fig.width=100%}
ridge_data_b %>%
  ggplot(aes(x = Cost, y = reorder(Team, -Place))) +
  geom_density_ridges(aes(fill = Team), scale = 3, size = 0.4, rel_min_height = 0.01, show.legend=FALSE) +
  ggtitle("Final Week Player Cost Distribution of Past 5 Seasons") +
  scale_x_continuous(limits = c(3000000, 14000000), labels = label_number(suffix = "", scale = 1e-6), breaks = seq(0,14000000,1000000)) +
  xlab("Player Cost (Millions)") + 
  ylab("Team") + 
  theme_light() +
  theme(plot.title = element_text(hjust = 0.5)) +
  scale_fill_viridis(discrete=TRUE)

```


```{r}
#EF: checking for duplicate player names and positions
df_2021_check <- df_orig %>%
  filter(Season == '2021') %>%
  mutate_at(c('FirstName'), ~replace_na(.,"NAMELESS")) %>%
  select(Surname, FirstName, PositionsList) %>%
  unite("player_id", c('Surname', 'FirstName', 'PositionsList'), sep= "_", remove=FALSE) %>%
  group_by(player_id) %>%
  summarise(count = n()) %>%
  arrange(desc(count))

remove(df_2021_check)

df_2021 <- df_orig %>%
  filter(Season == '2021') %>%
  mutate_at(c('FirstName'), ~replace_na(.,"NAMELESS")) %>%
  unite("player_id", c('Surname', 'FirstName', 'PositionsList'), sep= "_", remove=FALSE)

df_2021$player_id[df_2021$player_id == 'Davies_Ben_DEF' & df_2021$Team == 'TOT'] <- 'Davies_Ben_DEF_TOT'

# pc_graph_2021_beg <- fct_reorder(pc_graph_2021_beg$Surname, pc_graph_2021_beg$Cost)
remove(top_players_beg, df_2021_top_beg)

tp_5_each_team <- df_2021 %>%
  filter(Week == '37') %>%
  rename("team_grp" = "Team") %>%
  group_by(team_grp) %>%
  mutate(prank = rank(-TotalPoints)) %>%
  filter(prank <= 5) %>%
  select(player_id)

df_2021_tp_5 <- merge(df_2021, tp_5_each_team, by="player_id")

df_2021_tp_5 <- df_2021_tp_5 %>%
  select(Surname, Cost, Team, PointsLastRound, Week) %>%
  filter(Week > 0) %>%
  group_by(Team) %>%
  summarise(team_tot_pts = sum(PointsLastRound), team_tot_cost = sum(Cost)) %>%
  mutate(cost_pts = team_tot_cost / team_tot_pts) %>%
  mutate(pts_cost = team_tot_pts / team_tot_cost) %>%
  mutate(sub_group = 'Top 1-5') %>%
  merge(df_2021_team_key, by="Team") %>%
  mutate(image = NA)

tp_10_each_team <- df_2021 %>%
  filter(Week == '37') %>%
  rename("team_grp" = "Team") %>%
  group_by(team_grp) %>%
  mutate(prank = rank(-TotalPoints)) %>%
  filter(prank > 5 & prank <= 10) %>%
  select(player_id)

df_2021_tp_10 <- merge(df_2021, tp_10_each_team, by="player_id")

df_2021_tp_10 <- df_2021_tp_10 %>%
  select(Surname, Cost, Team, PointsLastRound, Week) %>%
  filter(Week > 0) %>%
  group_by(Team) %>%
  summarise(team_tot_pts = sum(PointsLastRound), team_tot_cost = sum(Cost)) %>%
  mutate(cost_pts = team_tot_cost / team_tot_pts) %>%
  mutate(pts_cost = team_tot_pts / team_tot_cost) %>%
  mutate(sub_group = 'Top 6-10') %>%
  merge(df_2021_team_key, by="Team")

delta_bar <- rbind(df_2021_tp_5, df_2021_tp_10)

remove(tp_5_each_team, tp_10_each_team)
```


```{r, fig.align = 'center', fig.width=100%}
ggplot(delta_bar, aes(reorder(Team, Place), cost_pts, fill=sub_group)) +
  geom_bar(position="dodge", stat="identity", width=0.6)+
  geom_image(aes(image=image, y = cost_pts + 250000), size=.05) +
  scale_y_continuous(limits = c(0, 5500000), breaks = seq(0,5500000,500000), labels = label_number(suffix = " M", scale = 1e-6)) +
  xlab(expression(atop("Team Ordered by Final Standings", paste("1st Place" %->% "20th Place")))) +
  ylab("Season Cost / Season Points") + 
  ggtitle("Costs Per Point of Top 5 Best Players on Each Team") +
  theme_light() +
  theme(plot.title = element_text(hjust = 0.5)) +
  labs(fill="Cost / Points") +
  theme(axis.text.x = element_text(size = 8, angle=25)) +
  scale_fill_manual(values = c("Top 1-5" = "#009E73", "Top 6-10" = "#E69F00"))

```


```{r}
# look at the greatest value change players over the season
gc_w0 <- df_2021 
gc_w0$Week <- as.numeric(gc_w0$Week)

gc_w0 <- gc_w0 %>%
    arrange(player_id, Week) %>%
    mutate(cost_diff = case_when(
      Week == 0 ~ 0,
      Week > 0 ~ (Cost - lag(Cost)))) %>%
    select(player_id, Week, Cost, PointsLastRound, cost_diff)

gc_w0 <- gc_w0 %>% 
  group_by(player_id) %>% 
  mutate(cum_cost_diff = cumsum(cost_diff)) %>%
  mutate(min_val = min(Cost)) %>%
  mutate(max_val = max(Cost)) %>%
  mutate(largest_diff = max_val - min_val) 

wk1_37_dummies <- gc_w0 %>%
  select(player_id, Week, Cost) %>%
  filter(Week == 37 | Week == 1) %>%
  pivot_wider(names_from = Week, values_from = Cost) %>%
  rename("Wk_1_val" = "1") %>%
  rename("Wk_37_val" = "37") %>%
  mutate(wk_1_wk37_diff = Wk_37_val - Wk_1_val) %>%
  mutate(delta37_dummy = case_when(
     wk_1_wk37_diff > 0 ~ 'Increase',
     wk_1_wk37_diff == 0 ~ 'No Change',
     wk_1_wk37_diff < 0 ~ 'Decrease',)) %>%
  select(player_id, delta37_dummy)

wk1_37_dummies$delta37_dummy <- factor(wk1_37_dummies$delta37_dummy, 
                                     levels = c("Increase", "No Change", "Decrease"))

neg_players <- gc_w0 %>% 
  filter(cum_cost_diff <= -300000) %>%
  select(player_id) %>%
  distinct()

neg_vals <- merge(gc_w0, neg_players, by="player_id", all = FALSE)
neg_vals <- merge(neg_vals, wk1_37_dummies, by="player_id")
neg_vals <- filter(neg_vals, !is.na(neg_vals$delta37_dummy))

pos_players <- gc_w0 %>% 
  filter(cum_cost_diff >= 300000) %>%
  select(player_id) %>%
  distinct()

pos_vals <- merge(gc_w0, pos_players, by="player_id", all = FALSE)
pos_vals <- merge(pos_vals, wk1_37_dummies, by="player_id")
pos_vals <- filter(pos_vals, !is.na(pos_vals$delta37_dummy))

```


```{r, fig.align = 'center', fig.width=100%}
ggplot(neg_vals, aes(x=Week, y=Cost, group = player_id, colour=factor(delta37_dummy))) +
  scale_y_continuous(limits = c(3500000, 13500000), breaks = seq(3500000,20000000,500000), labels = label_number(suffix = " M", scale = 1e-6)) +
  scale_x_continuous(breaks = seq(-0,37,1)) +
  geom_line(size=0.3, alpha=0.75) +
  geom_point(size=0.3, alpha = 0.75, stroke = 0) +
  theme_light() +
  labs(colour = "Weeks 1 vs 37") +
  ggtitle("Players Experiencing 300K or Greater \n Cumulitive Cost Decrease in 2021") +
  ylab("Cost in Week (Millions)") + xlab("Game Week") +
  theme(plot.title = element_text(hjust = 0.5)) +
  scale_colour_manual(values = c("Increase" = "#009E73", "No Change" = "#CC79A7", "Decrease" = "#E69F00")) +
  theme(axis.text.x = element_text(size = 7, angle=45))

ggplot(pos_vals, aes(x=Week, y=Cost, group = player_id, colour=factor(delta37_dummy))) +
  scale_y_continuous(limits = c(3500000, 13500000), breaks = seq(3500000,20000000,500000), labels = label_number(suffix = "", scale = 1e-6)) +
  scale_x_continuous(breaks = seq(0,37,1)) +
  geom_line(size=0.3, alpha=0.75) +
  geom_point(size=0.3, alpha = 0.75, stroke = 0) +
  theme_light() +
  labs(colour = "Weeks 1 vs 37") +
  ggtitle("Players Experiencing 300K or Greater \n Cumulitive Cost Increase in 2021") +
  ylab("Cost in Week (Millions)") + xlab("Game Week") +
  theme(plot.title = element_text(hjust = 0.5)) +
  scale_colour_manual(values = c("Increase" = "#009E73", "No Change" = "#CC79A7", "Decrease" = "#E69F00")) +
  theme(axis.text.x = element_text(size = 7, angle=45))

# https://rdrr.io/cran/ggthemes/man/colorblind.html

```
```{r}
# Top Players at beginning
top_players_beg <- df_2021 %>%
  filter(Week == 0) %>%
  arrange(desc(Cost)) %>%
  head(7) %>%
  select(player_id)

df_2021_top_beg <- merge(df_2021, top_players_beg, by="player_id")
df_2021_top_beg$Week <- as.numeric(df_2021_top_beg$Week)
df_2021_top_beg$Week <- df_2021_top_beg$Week + 1

pc_graph_2021_beg <- df_2021_top_beg %>%
  select(Surname, Cost, Week, SelectedByPercent) %>%
  arrange(Week, Surname)
```


```{r, fig.align = 'center', fig.width=100%}
g1 <- ggplot(pc_graph_2021_beg, aes(x=Week, y=SelectedByPercent, group = Surname, colour=factor(Surname))) +
  scale_y_continuous(limits = c(0,75), breaks = seq(0,100,10), labels = label_number(suffix = "%")) +
  scale_x_continuous(breaks = seq(0,38,1)) +
  geom_line() +
  geom_point(size=1.5, alpha = 0.75, stroke = 0) +
  labs(colour = "Player") +
  ylab("PercentageBy") + xlab("Game Week") +
  theme_light() +
  theme(axis.text.x = element_text(size = 7, angle=45)) +
  scale_colour_colorblind() +
  ggtitle("Highest Cost Players of 2021 Season") +
  theme(plot.title = element_text(hjust = 0.5)) 

g2 <- ggplot(pc_graph_2021_beg, aes(x=Week, y=Cost, group = Surname, colour=factor(Surname))) +
  scale_y_continuous(limits = c(11400000, 13300000), breaks = seq(11500000,13500000,500000), labels = label_number(suffix = "", scale = 1e-6)) +
  scale_x_continuous(breaks = seq(0,38,1)) +
  geom_line() +
  geom_point(size=1.5, alpha = 0.75, stroke = 0) +
  labs(colour = "Player") +
  ylab("Cost") + xlab("Game Week") +
  theme_light() +
  theme(axis.text.x = element_text(size = 7, angle=45)) +
  scale_colour_colorblind()

plot_grid(g1, g2, ncol = 1)

```
```{r, fig.align = 'center', fig.width=100%}

df_2021 <- df_2021 %>%
  arrange(TotalPoints)

ggplot(df_2021, aes(Week, player_id)) +
  geom_tile(aes(fill = PointsLastRound)) +
  ylab("Players") +
  labs(fill = "Points that Week") +
  scale_fill_gradient(low = "white", high = "blue" , limits=c(0,10))+
  theme_classic() +
  theme(axis.text.y=element_blank())

```
```{r, fig.align = 'center', fig.width=100%}
# cleveland dot plot
df_cleveland = df_orig %>% filter(Season != 2019)

df_cleveland %>%
  group_by(Team, Season) %>%
  summarise(TotalPoints = n()) %>%
  ggplot(aes(x = TotalPoints,
             y = fct_reorder2(Team, Season == 2021, TotalPoints, .desc = FALSE),
             color = factor(Season))) +
    geom_point() +
    ggtitle("Teams with the Most Points") +
    scale_colour_manual(values = c("#E69F00", "#009E73", "#0072B2", "#CC79A7")) + #colorblind friendly
    xlab("Total Points") +
    ylab("") +
    labs(color="Season") +
    theme_linedraw() +
    theme(plot.title = element_text(hjust = 0.5))
```

