# Proposal

## Research topic
Premier League Fantasy Football is a game where the participant is casted into a manager role of their own football (soccer) team, and the participant can draft players and compete against friends and strangers by comparing team performance. The real-life performance (goals, saves, assists, etc.) of that of the active players from the participants’ team rosters are used to score points for the team in the game. The game is a combination of strategy and luck, which provides a simulated experience of managing a professional sports team. Whereas identifying the top players is obvious to fantasy players, the skill lies in evaluating middle tier players, and identifying up-and-coming talent in the league. As such, the crux of the game is also that of our research questions – how can one identify whether a given player is overvalued or undervalued in fantasy football. Furthermore, we wish to explorer what the correlations are between player cost, player position, minutes played, and various performance parameters such as goals, saves, assists, and penalties. Along the way, we are curious about questions like: Which positions score the most points? How do the most expensive players at the beginning of of the season perform over time? Is there a cost-bias for players of similar performance on better teams? Do more expensive players always score the most points?

Before we dive deeper into the analysis of correlation between player cost and various performance parameters, we will first further debrief the game of Fantasy Premier League Football. When the participant first signs up to the game as a Fantasy Premier League (FPL) manager, the participant will be given a budget of 100 Pounds to spend on a roster of 15 players; of the 15 players, two are goalkeepers, five are defenders, five are midfielders, and three are forwards. The FPL manager must then create a team of 11 players of any formation, but must include at least one goalkeeper, three defenders, two midfielders, and one forward. Each Gameweek, the teams score points based on every player’s performance as measured in goals, assists, saves, and clean sheets (not conceding goals while playing for more than 60 minutes). 

As one can quickly realize, every FPL manager is essentially optimizing their budget to get the players that they perceive are the best in performance to cost. The game is a trade off. If superstar players are picked, then less budget is left for other strong middle tier players. If the FPL manage is able to identify cheap middle tier players with high performance, or player who are rising stars in real life, then the FPL manager will be able to score more points than other FPL managers and win the game. Therefore, FPL managers with good understanding of the cost performance correlations could have an advantage in building their team, and this project will attempt to discovery correlations between between player cost and all performance parameters.

## Data availability
### Date Source
The datasets that we will be using will be from fantasyoverlord.com, as linked below:
http://fantasyoverlord.com/FPL/History

Fantasy Overload has a scrapper built by Premier League Fantasy Football enthusiansts attempting to forecast player cost. On Fantasy Overlord’s “About” page, the website states that the data is webscrapped from The Premier League’s website, which routinely occurs every 30 minutes. The about page also indicates how long ago the data was last scraped. Data scraped by Fantasy Overload is logged and organized by Gameweek, and by season (year). From the link shown above, we will download all data files of interested into our repository for importing.

Due to the nature of the data, our data is objective in the sense that no sampling and polls are performed, and all scrapeable data are what is available to the all players from the game. The collector of the data has incentive to received the most accurate data possible; the data collector has no ulterior motiv in manipulating the data to demonstrate any political or financial claim. Therefore, we trust that the data we recieve are accurate, to the limit of the webscrapper.

### Data File Format and Importing
The data is organized in CSV files by Gameweek, spanning the full 2017 and 2021 seasons. Because the data is organized by Gameweek, and over the course of the full week, every player in the league plays, the CSV contains weekly aggregated data for every single player. Each season is composed of 38 match weeks, and each week is documented into a CSV file.

We plan to to download all of the CVS files and compile them into one primary dataset, by using R’s import capabilities. Since the data fields are consistent across CSV files, appending the data and labelling the match week & year of the appended data should be achievable.

### Data Fields Available
The CSV files will contain per-player information in: Name, Position, and Team; performance metrics in Total Points, Assists, Minutes Played, Goals Scored, Yellow Cards, Red Cards, Clean Sheets, Goals Conceded, and Saves; player cost metrics in Cost, Total Points Per Dollar, Average Points Per Dollar, and Price Change From Previous Week; player point metrics in Points Last Round, Total Points, and Average Points Per Week.

From the above data fields, we will explore correlation and find insights to answer the questions that we posed in the previous section.


