# Data 
## Sources

# Source: http://fantasyoverlord.com/FPL/History
# Season stats for 2017 to 2021 season
# Data pulled on Tue Nov 29 @11:54 AM

## Cleaning / transformation

```{r, fig.align = 'center'}
library(tidyverse)
# IMPORTANT COMMENTS: 2019 week 3 is an empty data file, it's missing
# 2016 data was missing weeks 1-5 so only did 2017

# EF: sets up empty dataframe with all required columns, will serve as master dataset

all_columns <- c("FirstName", "Surname", "Week", "Season", "PositionsList", "Team", 
                 "Cost", "PointsLastRound", "TotalPoints", "TransfersOut", "YellowCards", 
                 "GoalsConceded", "GoalsConcededPoints", "GoalsScored", "GoalsScoredPoints",
                 "TransfersOutRound", "PriceRise", "PriceFallRound", "LastSeasonPoints", 
                 "PriceFall", "PenaltiesMissed", "Form", "Bonus", "CleanSheets", 
                 "CleanSheetPoints", "Assists", "SelectedByPercent", "TransfersIn",
                 "OwnGoals","MinutesPlayed", "TransfersInRound", "PriceRiseRound", 
                 "RedCards")


import_columns <- c("FirstName", "Surname", "PositionsList", "Team", 
                 "Cost", "PointsLastRound", "TotalPoints", "TransfersOut", "YellowCards", 
                 "GoalsConceded", "GoalsConcededPoints", "GoalsScored", "GoalsScoredPoints",
                 "TransfersOutRound", "PriceRise", "PriceFallRound", "LastSeasonPoints", 
                 "PriceFall", "PenaltiesMissed", "Form", "Bonus", "CleanSheets", 
                 "CleanSheetPoints", "Assists", "SelectedByPercent", "TransfersIn",
                 "OwnGoals","MinutesPlayed", "TransfersInRound", "PriceRiseRound", 
                 "RedCards")

df_main <- data.frame(matrix(ncol = length(all_columns), nrow = 0))
colnames(df_main) <- all_columns

# EF: compiles all years and weeks 
years <- list('2017', '2018', '2019', '2020', '2021')
for (yr in years ) {
  print(yr)
  folder <- paste0("Data/main/season_", yr)
  all_weeks <- list.files(path=folder, pattern = "*.csv")
for (week in all_weeks) {
  data_file = paste0(folder, "/", week)
  temp_csv <- read_csv(data_file)
  temp_df  <- temp_csv[import_columns]
  
  # Applying time period and removing goalies
  temp_df$Week <- substr(week, 9,10)
  temp_df$Season <- yr
  temp_df = filter(temp_df, PositionsList != "GLK")
  
  
  df_main <- rbind(df_main, temp_df)
}
}

df_main <- df_main %>% 
   mutate(Cost = Cost / 1000000)            #convert cost to millions

write.csv(df_main, "Data/main/master.csv", row.names = FALSE)
```

```{r, fig.align = 'center'}
library(tidyverse)
library(ggplot2)

df <- read_csv("Data/main/master.csv")

PointCost <- df[df$Week == 37,]
d <- filter(PointCost, TotalPoints > 100)

ggplot(d, aes(x=Cost, y=TotalPoints)) + 
  geom_point(aes(colour = factor(Season))) +
  geom_smooth(method = "lm", se = FALSE) +
  ggtitle("Total Points in a Season against Cost (for players with more than 74 points)") +
  xlab("Cost (in Millions)") + 
  ylab("Total Points") +
  labs(colour = "Season")
  
  

```

```{r, fig.align = 'center'}

library(patchwork)

d <- d %>% 
   mutate(PointPerCost = TotalPoints / Cost) %>%
   mutate(PositionsList =factor(PositionsList, levels=c("DEF", "MID", "FWD")))

averagePPC <- mean(d$PointPerCost)

p1 <- ggplot(d, aes(x=PositionsList, y=TotalPoints)) + 
  geom_boxplot(outlier.size=0.9) +
  xlab("Poistion") + 
  ylab("Total Points")

p2 <- ggplot(d, aes(x=PositionsList, y=Cost)) + 
  geom_boxplot(outlier.size=0.9) +
  xlab("Poistion") + 
  ylab("Cost")


p3 <- ggplot(d, aes(x=PositionsList, y=PointPerCost)) + 
  geom_boxplot(outlier.size=0.9) +
  xlab("Poistion") + 
  ylab("Total Points per Cost") +
  geom_hline(aes(yintercept= averagePPC, linetype = "Average Points per Cost"), colour= 'red') +
  scale_linetype_manual(name = "", values = c(2, 2), guide = guide_legend(override.aes = list(color = c("red"))))

 
p1 + p2 + p3 + guide_area() + plot_layout(ncol = 2, guides = "collect")
 
  

```

```{r, fig.align = 'center'}

d <- d %>% 
  mutate(AssistPoints = Assists * 3) %>%
  mutate(MinutesPoints = 2*MinutesPlayed/90)

def <- d %>% 
  filter(PositionsList == "DEF") %>%
  mutate(GoalsScoredPoints = GoalsScored * 6) %>%
  mutate(CleanSheetPoints = CleanSheets * 4)

def <- def[, c("GoalsScoredPoints", "AssistPoints", "CleanSheetPoints", "Bonus", "MinutesPoints")]
defPoints <- colSums(def)

mid <- d %>% 
  filter(PositionsList == "MID") %>%
  mutate(GoalsScoredPoints = GoalsScored * 5) %>%
  mutate(CleanSheetPoints = CleanSheets * 1)

mid <- mid[, c("GoalsScoredPoints", "AssistPoints", "CleanSheetPoints", "Bonus", "MinutesPoints")]
midPoints <- colSums(mid)

fwd <- d %>% 
  filter(PositionsList == "FWD") %>%
  mutate(GoalsScoredPoints = GoalsScored * 3) %>%
  mutate(CleanSheetPoints = CleanSheets * 0)

fwd <- fwd[, c("CleanSheetPoints",  "Bonus",  "AssistPoints", "GoalsScoredPoints", "MinutesPoints")]
fwdPoints <- colSums(fwd)


points <- rbind(defPoints, midPoints, fwdPoints)

```

```{r, fig.align = 'center'}

library('vcd')
#mosaic(t(points))


library(ggmosaic)

df2 <- as.data.frame(points)

Position = c("DEF","MID","FWD")
df2['Position'] <- Position

df3 <- df2 %>%
  pivot_longer(!Position, names_to = "Type", values_to = "Freq")

df3$Freq <- as.integer(df3$Freq)  

ggplot(data = df3) +
  geom_mosaic(aes(x = product(Type, Position), fill=Type)) 


```

```{r, fig.align = 'center'}

d <- d %>% 
  mutate(AssistPoints = Assists * 3)

def <- d %>% 
  filter(PositionsList == "DEF") %>%
  mutate(GoalsScoredPoints = GoalsScored * 6) %>%
  mutate(CleanSheetPoints = CleanSheets * 4)

def <- def[, c("GoalsScoredPoints", "AssistPoints", "CleanSheetPoints", "Bonus")]
defPoints <- colMeans(def)

mid <- d %>% 
  filter(PositionsList == "MID") %>%
  mutate(GoalsScoredPoints = GoalsScored * 5) %>%
  mutate(CleanSheetPoints = CleanSheets * 1)

mid <- mid[, c("GoalsScoredPoints", "AssistPoints", "CleanSheetPoints", "Bonus")]
midPoints <- colMeans(mid)

fwd <- d %>% 
  filter(PositionsList == "FWD") %>%
  mutate(GoalsScoredPoints = GoalsScored * 3) %>%
  mutate(CleanSheetPoints = CleanSheets * 0)

fwd <- fwd[, c("GoalsScoredPoints", "AssistPoints", "CleanSheetPoints", "Bonus")]
fwdPoints <- colMeans(fwd)


points <- rbind(defPoints, midPoints, fwdPoints)

```


```{r, fig.align = 'center'}

pts <- as.data.frame(points)

Position = c("DEF","MID","FWD")
pts['Position'] <- Position

pts <- pts %>%
  pivot_longer(!Position, names_to = "PointType", values_to = "Count") %>%
  mutate(Position = factor(Position, levels=c("DEF", "MID", "FWD"))) %>%
  mutate(PointType = factor(PointType, levels=c("CleanSheetPoints", "Bonus",  "AssistPoints", "GoalsScoredPoints")))



ggplot(pts, aes(fill=PointType, y=Count, x=Position)) + 
    geom_bar(position="stack", stat="identity") +
    xlab("Position") + 
    ylab("Average Positive Points per Player") 


```

```{r, fig.align = 'center'}

pos <- as.data.frame( table(d['PositionsList']) / length(d$PositionsList) )

p1 <- ggplot(pos, aes(fill=PositionsList, y=Freq*100, x=1 , label = as.integer(Freq*100))) + 
    geom_bar(position="stack", stat="identity") +
    coord_flip() +
    ylab("Proprtion of players in each position") +
    geom_text(size = 3.5, position = position_stack(vjust = 0.5)) +
    theme(axis.text.y=element_blank(), axis.ticks.y=element_blank())


p2 <- ggplot(d, aes(x=SelectedByPercent, y=100*(..count..)/sum(..count..))) + 
  geom_histogram(binwidth=1.5) +
  facet_grid(cols = vars(PositionsList))


p1 + p2 + plot_layout(nrow = 2, heights = c(1, 2.5) )


```

```{r, fig.align = 'center'}

ggplot(d, aes(x=SelectedByPercent, y=PointPerCost)) + 
  geom_point(aes(colour = PositionsList)) +
  labs(colour = "Position")

```

